### PR TITLE
cleanup too old druid emited metrics

### PR DESCRIPTION
**Pull request by exherb**

### CODE REVIEW

**Comment by iamabhishek-dubey** [comment]
@exherb have you tested this for older druid versions as well?

**Comment by exherb** [comment]
> @exherb have you tested this for older druid versions as well?

no, I just tested in k8s cluster with newest version.

**Comment by iamabhishek-dubey** [comment]
@exherb please resolve the conflicts so I can merge the PR

**Comment by exherb** [comment]
> @exherb please resolve the conflicts so I can merge the PR

done

**Pull request merged**
