### PR TITLE
Add metric druid_worker_capacity_total

### PR DESCRIPTION
**Pull request by Aka-shi**
Resolves #83

### CODE REVIEW

**Comment by Aka-shi** [comment]
@iamabhishek-dubey raised a different PR. Please check.

**Comment by Aka-shi** [comment]
@iamabhishek-dubey raised a different PR. Please check.

**Review by iamabhishek-dubey — APPROVED** [review]
LGTM

**Comment by iamabhishek-dubey** [comment]
Const metric cannot be used in this case, I am reverting the change

**Pull request merged**
